name=Portenta_SDRAM
version=1.0
author=Arduino
maintainer=Arduino <info@arduino.cc>
sentence=Interact with external SDRAM chip on Portenta H7
paragraph=With this library you can allocate and access the external SDRAM chip available on the Portenta H7.
category=Other
url=https://github.com/arduino/ArduinoCore-zephyr/tree/main/libraries/Zephyr_SDRAM
architectures=zephyr_main
