name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: zephyrprojectrtos/ci:latest
    env:
      CMAKE_PREFIX_PATH: /opt/toolchains
      PR_NUMBER: ${{ github.event.number }}
    steps:
      - name: Initialize
        run: |
          mkdir build && cd build
          west init -m https://github.com/${{ github.repository }}
          cd modules/lib/ArduinoCore-zephyr/
          git fetch origin ${{ github.ref }}
          git checkout FETCH_HEAD
          cd -
          west update

      - name: Build fade
        working-directory: build
        run: |
          west build -p -b arduino_nano_33_ble//sense modules/lib/ArduinoCore-zephyr/samples/fade

      - name: Build i2cdemo
        working-directory: build
        run: |
          west build -p -b ek_ra8d1 modules/lib/ArduinoCore-zephyr/samples/i2cdemo

      - name: Build adc
        working-directory: build
        run: |
          west build -p -b arduino_nano_33_ble/nrf52840/sense modules/lib/ArduinoCore-zephyr/samples/analog_input