name: Build native Zephyr samples

on: [push, pull_request]

jobs:
  build:
    name: Build native Zephyr samples
    runs-on: ubuntu-latest
    container: zephyrprojectrtos/ci:latest
    env:
      CMAKE_PREFIX_PATH: /opt/toolchains
      CCACHE_IGNOREOPTIONS: -specs=*
      REPOSITORY: ${{ github.event.pull_request.head.repo.full_name || github.repository }}
      BRANCH: ${{ github.event.pull_request.head.ref || github.ref_name }}
    steps:
      - name: Initialize
        run: |
          mkdir build && cd build
          west init -m https://github.com/${{ env.REPOSITORY }} --mr ${{ env.BRANCH }}
          west update -o=--filter=tree:0

      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          verbose: 1

      - name: Build fade
        working-directory: build
        run: |
          west build -p -b arduino_nano_33_ble//sense modules/lib/ArduinoCore-zephyr/samples/fade

      - name: Build i2cdemo
        working-directory: build
        run: |
          west build -p -b ek_ra8d1 modules/lib/ArduinoCore-zephyr/samples/i2cdemo

      - name: Build adc
        working-directory: build
        run: |
          west build -p -b arduino_nano_33_ble/nrf52840/sense modules/lib/ArduinoCore-zephyr/samples/analog_input
