name: Package core

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ZEPHYR_SDK_INSTALL_DIR: /opt/zephyr-sdk-0.16.8
    steps:
      - name: Install toolchain
        working-directory: /opt
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends git cmake wget python3-pip ninja-build
          wget https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v0.16.8/zephyr-sdk-0.16.8_linux-x86_64_minimal.tar.xz
          tar xf zephyr-sdk-0.16.8_linux-x86_64_minimal.tar.xz && cd zephyr-sdk-0.16.8 && ./setup.sh -t arm-zephyr-eabi -c

      - uses: actions/checkout@v4

      - name: Initialize
        run: |
          ./extra/bootstrap.sh
          ./extra/build_all.sh
          ./extra/package.sh `git describe --always`
          mv ../arduino-core-zephyr-llext* .

      - name: Archive core
        uses: actions/upload-artifact@v4
        with:
          name: Core
          path: arduino-core-zephyr-llext*

      - name: Create Blink sketch
        run: |
          mkdir extra/Blink/
          wget https://raw.githubusercontent.com/arduino/arduino-examples/refs/heads/main/examples/01.Basics/Blink/Blink.ino
          mv Blink.ino extra/Blink/

      - name: Compile Blink
        uses: arduino/compile-sketches@main
        with:
          fqbn: arduino:zephyr:giga
          platforms: |
            # Use Board Manager to install the latest release of Arduino Zephyr Boards to get the toolchain
            - name: "arduino:zephyr"
              source-url: "https://downloads.arduino.cc/packages/package_zephyr_index.json"
            - source-path: "./"
              name: "arduino:zephyr"
          sketch-paths: |
            extra/Blink
          verbose: 'false'
          enable-deltas-report: 'false'
