name: Package, test and upload core

on:
  push:
    branches:
      - arduino
  pull_request:

jobs:

  package-core:
    name: Build and package core
    runs-on: ubuntu-latest
    env:
      ZEPHYR_SDK_INSTALL_DIR: /opt/zephyr-sdk-0.16.8
      CCACHE_IGNOREOPTIONS: -specs=*
    outputs:
      CORE_TAG: ${{ env.CORE_TAG }}
      CORE_ARTIFACT: ${{ env.CORE_ARTIFACT }}
      BOARD_NAMES: ${{ env.BOARD_NAMES }}
    steps:
      - name: Install toolchain
        working-directory: /opt
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends git cmake wget python3-pip ninja-build ccache
          wget -nv https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v0.16.8/zephyr-sdk-0.16.8_linux-x86_64_minimal.tar.xz
          tar xf zephyr-sdk-0.16.8_linux-x86_64_minimal.tar.xz && cd zephyr-sdk-0.16.8 && ./setup.sh -t arm-zephyr-eabi -c

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Initialize
        run: |
          ./extra/bootstrap.sh -o=--filter=tree:0
          echo "CORE_TAG=$(git describe --always)" >> "$GITHUB_ENV"
          echo "CORE_ARTIFACT=ArduinoCore-zephyr-$(git describe --always)" >> "$GITHUB_ENV"
          echo "BOARD_NAMES=[ $(cat boards.txt | grep '^[^#]*\.build\.variant' | cut -d '.' -f 1 | xargs printf '"%s",' | sed -e 's/,$//') ]" >> "$GITHUB_ENV"

      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          verbose: 1

      - name: Build variants
        run: |
          ./extra/build_all.sh -f

      - name: Package
        run: |
          ./extra/package.sh ${{ env.CORE_TAG }}
          mv ../${{ env.CORE_ARTIFACT }}.tar.bz2 .

      - name: Archive core
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.CORE_ARTIFACT }}
          path: ${{ env.CORE_ARTIFACT }}.tar.bz2

  test-core:
    name: Test arduino:zephyr:${{ matrix.board }}
    runs-on: ubuntu-latest
    needs: package-core
    strategy:
      matrix:
        board: ${{ fromJSON( needs.package-core.outputs.BOARD_NAMES ) }}
      fail-fast: false
    env:
      FQBN: arduino:zephyr:${{ matrix.board }}
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: ${{ needs.package-core.outputs.CORE_ARTIFACT }}

      - name: Set up core
        run: |
          tar xf ${{ needs.package-core.outputs.CORE_ARTIFACT }}.tar.bz2

      - name: Create Blink sketch
        run: |
          mkdir Blink/
          wget -nv https://raw.githubusercontent.com/arduino/arduino-examples/refs/heads/main/examples/01.Basics/Blink/Blink.ino -P Blink/

      - name: Compile Blink for ${{ env.FQBN }}
        uses: arduino/compile-sketches@main
        with:
          fqbn: ${{ env.FQBN }}
          platforms: |
            # Use Board Manager to install the latest release of Arduino Zephyr Boards to get the toolchain
            - name: "arduino:zephyr"
              source-url: "https://downloads.arduino.cc/packages/package_zephyr_index.json"
            - name: "arduino:zephyr"
              source-path: "ArduinoCore-zephyr"
          sketch-paths: Blink
          verbose: 'false'
          enable-deltas-report: 'false'
